name: jds-arx-poc
channels:
- conda-forge
- defaults
dependencies:
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - markdown=3.1.1
  - notebook=6.0.1
  - pandas=0.25.2
  - pip=19.3.1
  - python=3.6.9
  - scipy=1.3.1
  - matplotlib=3.1.1
  - pillow=6.2.0
  - pylint=2.4.3
  - py-opencv=3.4.2
  - google-api-core=1.14.3
  - google-cloud-storage=1.20.0
  - pip:
    - tensorflow==1.15.0